
package proxy;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReleveWS", targetNamespace = "http://QuestionC/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReleveWS {


    /**
     * 
     * @return
     *     returns proxy.Releve
     * @throws JAXBException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReleve", targetNamespace = "http://QuestionC/", className = "proxy.GetReleve")
    @ResponseWrapper(localName = "getReleveResponse", targetNamespace = "http://QuestionC/", className = "proxy.GetReleveResponse")
    @Action(input = "http://QuestionC/ReleveWS/getReleveRequest", output = "http://QuestionC/ReleveWS/getReleveResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://QuestionC/ReleveWS/getReleve/Fault/JAXBException")
    })
    public Releve getReleve()
        throws JAXBException_Exception
    ;

}
